version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sha4ycvpx2jh"
s3_prefix = "lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"hta-simple-lambda-s3-bucket\""
