AWSTemplateFormatVersion: 2010-09-09
Description: Sample for using cfn init
Parameters:
  TagKey:
    Description: EC2 Tag Key
    Type: String
    Default: cfn-init
  TagValue:
    Description: EC2 Tag Valie
    Type: String
    Default: helper
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Metadata:
      AWS::CloudFormation::Init:
        configSets: 
          InstallAndRun: 
            - "config-ec2"
        config-ec2:
          packages:
            yum:
              ruby: []
          files:
            /home/ec2-user/install:
              mode: "000755"
              source:
                'Fn::Join':
                  - ''
                  - - 'https://aws-codedeploy-'
                    - !Ref 'AWS::Region'
                    - '.s3.amazonaws.com/latest/install'
          commands:
            00-install-agent:
              command: "./install auto"
              cwd: "/home/ec2-user/"
    Properties:
      ImageId: "ami-01d025118d8e760db"
      InstanceType: "t2.micro"
      KeyName: "cfn-key"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "io1"
            Iops: 200
            DeleteOnTermination: true
            VolumeSize: 20
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              # Install the files and packages from the metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource MyEC2Instance '
            - '         --configsets InstallAndRun '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
