AWSTemplateFormatVersion: 2010-09-09
Description: Simple repository on cloud
Resources:
  MyBuilderPermission:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: hta-cloudformation-codecommit
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - 'codecommit:*'
                Resource:
                  - '*'
        - PolicyName: hta-cloudformation-cloudwatch
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:*'
                Resource:
                  - '*'
  MySimpleRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MySimpleRepo
      RepositoryDescription: Simpleest Repository with Cfn
      Code:
        S3:
          Bucket: hta-cloudformation-bucket
          Key: DeveloperTheory/Code.zip
  MyBuilder:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - MySimpleRepo
    Properties:
      ServiceRole: !Ref MyBuilderPermission
      Artifacts: 
        Type: 'NO_ARTIFACTS'
      Source:
        Type: 'CODECOMMIT'
        Location: !Sub 'https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${MySimpleRepo.Name}'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0