AWSTemplateFormatVersion: 2010-09-09
Description: Simple repository on cloud
Resources: 
  MySimpleRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MySimpleRepo
      RepositoryDescription: Simpleest Repository with Cfn
      Code:
        S3:
          Bucket: hta-cloudformation-bucket
          Key: DeveloperTheory/code.zip

