AWSTemplateFormatVersion: 2010-09-09
Description: Web Identity Stack (Flask + Elastic Beanstalk)
Parameters:
  EBEnvironmentName:
    Description: Environment Name
    Type: String
    Default: FlaskEnvironment
Resources:
  EBFlaskApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Flask Application
  EBFlaskApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        !Ref EBFlaskApplication
      Description: AWS ElasticBeanstalk Flask Application Version
      SourceBundle:
        S3Bucket: hta-cloudformation-bucket
        S3Key: Elasticbeanstalk/Flask/WebIdentity.zip
  EBConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref EBFlaskApplication
      Description: AWS ElasticBeanstalk Flask Configuration Template
      OptionSettings:
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: StreamLogs
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: DeleteOnTerminate
        Value: 'false'
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '2'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:elasticbeanstalk:environment:process:default
        OptionName: StickinessEnabled
        Value: 'true'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: application
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: cfn-key
      SolutionStackName: 64bit Amazon Linux 2 v3.0.3 running Python 3.7
  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties: 
      ApplicationName: !Ref EBFlaskApplication
      Description: AWS Elastic Beanstalk Environment running Flask Web Identity Application
      EnvironmentName: !Ref EBEnvironmentName
      TemplateName: !Ref EBConfigurationTemplate
      VersionLabel: !Ref EBFlaskApplicationVersion