version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-lambda-integration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sha4ycvpx2jh"
s3_prefix = "sqs-lambda-integration"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

